# Generated by Django 6.0.3 on 2026-04-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
