# Generated by Django 6.0.3 on 2026-04-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
