# Generated by Django 6.0.3 on 2026-04-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0005_reservation_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='places',
        ),
    ]
