# Generated by Django 6.0.3 on 2026-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0006_remove_reservation_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='gatunek',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
