# Generated by Django 6.0.3 on 2026-04-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0007_movie_gatunek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='gatunek',
            new_name='genre',
        ),
    ]
