# Generated by Django 6.0.3 on 2026-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0009_genre_delete_type_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
