# Generated by Django 6.0.3 on 2026-04-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0010_alter_reservation_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
