# Generated by Django 6.0.3 on 2026-04-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0011_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=135),
            preserve_default=False,
        ),
    ]
