# Generated by Django 6.0.3 on 2026-04-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='kino_app.actor'),
        ),
    ]
