# Generated by Django 6.0.3 on 2026-04-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0014_alter_movie_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('students_count', models.IntegerField()),
                ('movie_title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
