# Generated by Django 6.0.3 on 2026-04-22 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0015_schoolbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbooking',
            name='seans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kino_app.seans'),
        ),
    ]
