# Generated by Django 6.0.3 on 2026-04-22 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0016_schoolbooking_seans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolbooking',
            name='movie_title',
        ),
        migrations.AddField(
            model_name='schoolbooking',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kino_app.movie'),
        ),
    ]
