# Generated by Django 6.0.3 on 2026-04-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0017_remove_schoolbooking_movie_title_schoolbooking_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seans',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seanses', to='kino_app.movie'),
        ),
    ]
