# Generated by Django 6.0.3 on 2026-04-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0019_privatereservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatereservation',
            name='movie_title',
        ),
    ]
