# Generated by Django 6.0.3 on 2026-04-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0021_reservation_email_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('premiere_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('poster_url', models.URLField(default='https://picsum.photos', max_length=500)),
            ],
        ),
    ]
