# Generated by Django 6.0.3 on 2026-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0022_upcomingmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingmovie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingmovie',
            name='poster_url',
            field=models.URLField(max_length=500),
        ),
    ]
