# Generated by Django 6.0.3 on 2026-04-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0023_upcomingmovie_trailer_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingmovie',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='upcomingmovie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
